version: '3'
services:
    web:
        build: .
        stdin_open: true
        tty: true
        ports: 
            - "8081:8081"
            - "8001:8001"
        volumes:
            - "/app/node_modules" 
            - ".:/app"
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true