import { Form } from 'vform'

const Vmasterfileform = new Form({
  primekey: '',
  avatar__: '',
  empl_cde: '',
  empl_cd2: '',
  asso_cde: '',
  chro_num: '',
  last_nme: '',
  frst_nme: '',
  midl_nme: '',
  midl_ini: '',
  nickname: '',
  birthday: '',
  sex_____: '',
  cvilstat: '',
  address1: '',
  address2: '',
  address3: '',
  cel_numb: '',
  dte_hire: '',
  dte_rglr: '',
  dte_rsgn: '',
  dte_eoc_: '',
  pos_code: '',
  emp_stat: '',
  workstat: '',
  workarea: '',
  grp_lvl1: '',
  grp_lvl2: '',
  grp_lvl3: '',
  min_wage: '',
  trainee_: '',
  shft_cde: '',
  alw_flex: '',
  compweek: '',
  rest_day: '',
  rest_da2: '',
  bio_reqd: '',
  tmeinout: '',
  earlytme: '',
  alw_ot__: '',
  alw_nsd_: '',
  alw_hol_: '',
  tax_numb: '',
  sss_numb: '',
  pag_ibig: '',
  philhlth: '',
  rate_typ: '',
  alw_payr: '',
  paygroup: '',
  comp_sss: '',
  comp_med: '',
  comp_pgi: '',
  comp_tax: '',
  tax_type: '',
  tax_over: '',
  pgbig_cd: '',
  bankfile: '',
  acct_typ: '',
  acct_num: ''
})

export { Vmasterfileform }
